# Generated by Django 3.1.5 on 2021-04-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foo_auth', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_to_assets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_to_code',
        ),
    ]
