# Generated by Django 3.2.5 on 2021-08-07 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('code', models.CharField(db_index=True, default=portal.models.generate_code, max_length=100)),
                ('account_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_synced', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_connected', models.BooleanField(default=False)),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.room')),
            ],
        ),
    ]
