# Generated by Django 3.2.5 on 2021-08-10 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_camera_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message', models.CharField(db_index=True, default='', max_length=100)),
                ('acccess_granted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.employee')),
            ],
        ),
    ]
