# Generated by Django 3.2.5 on 2021-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='employee',
        ),
        migrations.AddField(
            model_name='event',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='subject',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
