# Generated by Django 3.2.5 on 2021-08-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20210810_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='acccess_granted',
            new_name='access_granted',
        ),
    ]
