# Generated by Django 3.2.5 on 2021-08-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_acccess_granted_event_access_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
