# Generated by Django 3.2.5 on 2021-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_event_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='camera',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
