# Generated by Django 3.2.5 on 2021-08-10 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0009_event_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='account_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='foo_auth.user'),
            preserve_default=False,
        ),
    ]
